### PR TITLE
v1.2.2-Fabric

### PR DESCRIPTION
**Pull request by Spongecade**
- Removed jcenter repo from settings.gradle
- Added "celeri" as a contributor
- Edited the readme

Merging this does mess up your publishing workflow though :/

### CODE REVIEW

**Comment by Spongecade** [comment]
Pushing this does kind of mess up your established workflow though :/

**Comment by c-leri** [comment]
After reviewing your project I feel like it wouldn't work as just the 1.16.5 version of Dynamic Music Updated.
What you've done is a lot closer to the original code base of LudoCrypt's Dynamic Music and thus I feel like it would actually be better if it remained as its own project !

**Comment by Spongecade** [comment]
Yeah I agree that my branch doesn't really fit into your fork. I kind of held off on creating the forge pr as a result. I'll be publishing DynamicMusic: Legacy soon but honestly thanks for keeping this mod updated!

**Comment by c-leri** [comment]
No issue ! Good luck on your side !

**Pull request closed without merging**
